language: generic

dist: bionic

if: tag IS present OR branch = master

jobs:
  include:
    - stage: Build and push images to DockerHub
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - make submodules
      - make build
      - make push
